# services:
#   db:
#     image: postgres:16-alpine
#     environment:
#       POSTGRES_DB: processos
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       retries: 5
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   backend:
#     build:
#       context: ./backend
#     environment:
#       DATABASE_URL: postgresql://postgres:postgres@db:5432/processos?schema=public
#       PORT: 3000
#       CORS_ORIGIN: http://localhost:5173
#     depends_on:
#       - db
#     ports:
#       - "3000:3000"
#     command: sh -c "npx prisma db push && node src/server.js"

#   frontend:
#     build:
#       context: ./frontend
#     environment:
#       VITE_API_URL: http://localhost:3000
#     ports:
#       - "5173:5173"
#     command: sh -c "npm ci || npm i && npm run dev -- --host 0.0.0.0"
#     depends_on:
#       - backend

# volumes:
#   db_data:

services:
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: file:./dev.db
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build:
      context: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm ci || npm i && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
